FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && \
    apt-get install -y wget gnupg curl unzip fonts-freefont-ttf && \
    apt-get install -y libglib2.0-0t64 libnss3 libnspr4 libdbus-1-3 \
        libatk1.0-0t64 libatk-bridge2.0-0t64 libatspi2.0-0t64 \
        libx11-6 libxcomposite1 libxdamage1 libxext6 libxfixes3 \
        libxrandr2 libgbm1 libxcb1 libxkbcommon0 libasound2t64 \
        libcups2 libdrm2 libxshmfence1 libxkbcommon-x11-0 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN playwright install --force chromium
RUN playwright install-deps

COPY . .

CMD ["python", "main.py"]